name: StrangeBaconGrease
version: 1.0
Author: Fruitloopins
main: com.fruitloopins.StrangeBaconGrease.Main
api-version: 1.18
commands:
   sbg:
      description: Gives Strange Bacon Grease to the player.
      usage: /<command>
      permission: strangebacongrease.sbg